### ISSUE TITLE
undefined method 'new' for BigDecimal:Class

### ISSUE THREAD

**Issue by Noctualis** [bigcartel-themes/ranger#6]
Hello!

I'm having an issue running `dugway server ` for this theme and get the error in the screenshot below. I am on Dugway version 1.0.3 on Windows 10 with ruby version 2.7.2. I have been able to use `dugway server` on the the theme 'parade-master' and create a new theme, so I believe it has to do with this specific theme. My goal is to edit a few features on this theme to use for my site, so I would be grateful for any help!

![image](https://user-images.githubusercontent.com/57472319/106707620-846fa400-65bf-11eb-9f61-adb25cea1982.png)

**Comment by nickendle** [comment]
@Noctualis hmm, it seems unlikely that this BigDecimal error would be specific to the Ranger theme, those kinds of errors are usually related to ruby. Can you post the full stack trace to help us understand out what might be happening here?

**Comment by Noctualis** [comment]
Ah, so is it just that this theme happens to use that class while the others don't? 

I'm new to ruby, how/where do I get the full stack trace? Would rather not guess and waste time.

**Comment by nickendle** [comment]
@Noctualis the full contents in the left hand table would help! Or if you see the same error appear in the command line, pasting that would help too. 

And just to make sure -- have you edited any of the code yet? Can you also try pulling down the latest master (A couple minor fixes were just pushed) and running `dugway server` again?

**Comment by Noctualis** [comment]
No errors show in the command line! The only change I have from the master is adding a .dugway.json file (I just copied it from another template). I pulled the new master and tried `dugway server` again and got the same results (the ones in the screenshots)

I noticed this template uses navigation.js and cart.js whereas the other ones I tried to run did not, everything else seemed pretty similar. 

Here is that left hand table. Please let me know if these images are too huge and I can try to edit it. I ordered them so that they would read the same way it shows on the page. 
![part8](https://user-images.githubusercontent.com/57472319/106783468-58810c80-6619-11eb-8373-5712ab1ad91c.PNG)
![part7](https://user-images.githubusercontent.com/57472319/106783465-57e87600-6619-11eb-895e-019a5483efac.PNG)
![part6](https://user-images.githubusercontent.com/57472319/106783474-5919a300-6619-11eb-925f-ad3992e9298b.PNG)
![part5](https://user-images.githubusercontent.com/57472319/106783473-5919a300-6619-11eb-8cfe-b1ff43b9dc7e.PNG)
![part4](https://user-images.githubusercontent.com/57472319/106783472-58810c80-6619-11eb-84d4-ef297a0577a9.PNG)
![part3](https://user-images.githubusercontent.com/57472319/106783471-58810c80-6619-11eb-815c-8e667ca55557.PNG)
![part2](https://user-images.githubusercontent.com/57472319/106783470-58810c80-6619-11eb-8fd3-aefaa9c12380.PNG)
![part1](https://user-images.githubusercontent.com/57472319/106783469-58810c80-6619-11eb-9772-710abc6afee2.PNG)

**Comment by nickendle** [comment]
@Noctualis thanks! Can you also paste the contents of your `.dugway.json` file?

**Comment by Noctualis** [comment]
Sure! Just used the default one generated by `dugway create mytheme`

```
// Use this file to test your theme with different stores and customization variations.
// Learn more at: // https://github.com/bigcartel/dugway#testing-your-theme
// DON'T CHECK THIS FILE INTO SOURCE CONTROL

{

  // Use data from any store to make sure your theme looks great with all sorts of products, pages,
  // categories, and more. Just give us the subdomain. Default is "dugway" for dugway.bigcartel.com.

  // "store": {
  //   "subdomain": "mystore"
  // },

  // Simulate the customization done by store owners by passing values to different variables.
  // Default values are based on the "default" for each setting in your settings.json.

  // "customization": {
  //   "logo": {
  //     "url": "http://placehold.it/200x50/000000/ffffff&text=My+Logo",
  //     "width": 200,
  //     "height": 50
  //   },
  //   "background_color": "#CCCCCC",
  //   "show_search": true,
  //   "twitter_username": "bigcartel"
  // }
}

```

**Comment by brettchalupa** [comment]
@Noctualis thanks for your patience here. We've been investigating and working on this, and this PR will help prevent the error from happening: https://github.com/bigcartel/dugway/pull/186

There's a chance, though, that it won't work on Ruby 2.7.x, since we have some older dependencies that haven't been updated to support newer Rubies.

If possible, downgrading to Ruby 2.6.x or earlier will fix your issue right away.

And the aforementioned PR will make this more clear in the future for instances of this problem arising again.

Let us know if you run into any more issues after downgrading your Ruby.

**Comment by brettchalupa** [comment]
@Noctualis running `gem install dugway` will install the latest ver for you. I just released the new version. I'm not sure if that fixes it in Ruby 2.7.0, but it may! If not, the Ruby downgrade should do it.

**Comment by Noctualis** [comment]
it worked on 2.7.0 after updating! Thanks so much for the help.

**Comment by brettchalupa** [comment]
@Noctualis Excellent, glad to hear it!
